spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/movieaxis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false


movie:
  base:
    path: http://127.0.0.1:8080
